### ISSUE TITLE
gym.configuration can't be find

### ISSUE THREAD

**Issue by AaronZhu2018** [vivek3141/super-mario-neat#1]
I follow the guide you metion.
I have this problem
![image](https://user-images.githubusercontent.com/25722824/50732942-c0f12b80-11be-11e9-9e0e-750a20b878bb.png)

**Comment by vivek3141** [comment]
Hi,
That line is not there in the original code. Maybe you edited something?
You can delete that line or run: git pull origin master
Thanks,
Vivek
